### ISSUE TITLE
createGraphicsPipelinesUnique and createComputePipelinesUnique stopped compiling on MSVC 14.24.28314

### ISSUE THREAD

**Issue by YaaZ** [KhronosGroup/Vulkan-Hpp#674]
Probably related to https://github.com/KhronosGroup/Vulkan-Hpp/issues/659
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\xmemory(671): error C2280: 'vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>::UniqueHandle(const vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> &)': attempting to reference a deleted function
C:\VulkanSDK\1.2.141.2\Include\vulkan/vulkan.hpp(831): note: see declaration of 'vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>::UniqueHandle'
C:\VulkanSDK\1.2.141.2\Include\vulkan/vulkan.hpp(831): note: 'vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>::UniqueHandle(const vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> &)': function was explicitly deleted
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\xmemory(1497): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,_Ty&>(_Alloc &,_Objty *const ,_Ty &)' being compiled
        with
        [
            _Alloc=std::allocator<vk::UniquePipeline>,
            _Ty=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,
            _Objty=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\xmemory(1498): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,_Ty&>(_Alloc &,_Objty *const ,_Ty &)' being compiled
        with
        [
            _Alloc=std::allocator<vk::UniquePipeline>,
            _Ty=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,
            _Objty=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\xmemory(1533): note: see reference to function template instantiation 'void std::_Uninitialized_backout_al<_Alloc>::_Emplace_back<_Ty&>(_Ty &)' being compiled
        with
        [
            _Alloc=std::allocator<vk::UniquePipeline>,
            _Ty=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\xmemory(1533): note: see reference to function template instantiation 'void std::_Uninitialized_backout_al<_Alloc>::_Emplace_back<_Ty&>(_Ty &)' being compiled
        with
        [
            _Alloc=std::allocator<vk::UniquePipeline>,
            _Ty=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1591): note: see reference to function template instantiation 'vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *std::_Uninitialized_copy<_Iter,std::allocator<vk::UniquePipeline>>(const _InIt,const _InIt,vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *,_Alloc &)' being compiled
        with
        [
            _Iter=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *,
            _InIt=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *,
            _Alloc=std::allocator<vk::UniquePipeline>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(530): note: see reference to function template instantiation 'vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *std::vector<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,std::allocator<vk::UniquePipeline>>::_Ucopy<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>*>(_Iter,_Iter,vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *)' being compiled
        with
        [
            _Iter=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(530): note: see reference to function template instantiation 'vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *std::vector<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,std::allocator<vk::UniquePipeline>>::_Ucopy<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>*>(_Iter,_Iter,vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *)' being compiled
        with
        [
            _Iter=vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(519): note: while compiling class template member function 'std::vector<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,std::allocator<vk::UniquePipeline>>::vector(const std::vector<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,std::allocator<vk::UniquePipeline>> &)'
C:\VulkanSDK\1.2.141.2\Include\vulkan/vulkan.hpp(13434): note: see reference to function template instantiation 'std::vector<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,std::allocator<vk::UniquePipeline>>::vector(const std::vector<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,std::allocator<vk::UniquePipeline>> &)' being compiled
C:\VulkanSDK\1.2.141.2\Include\vulkan/vulkan.hpp(13447): note: see reference to class template instantiation 'std::vector<vk::UniqueHandle<vk::Pipeline,vk::DispatchLoaderDynamic>,std::allocator<vk::UniquePipeline>>' being compiled

```

**Comment by asuessenbach** [comment]
You're right, this is related to #659.
We're working on a fix for it...

**Comment by YaaZ** [comment]
@asuessenbach isn't the fix released yet? Cause I'm getting the same error on latest VulkanSDK 1.2.148.1

**Comment by asuessenbach** [comment]
@YaaZ as mentioned in #680, this can't be resolved by vulkan.hpp.

**Comment by YaaZ** [comment]
@asuessenbach yes, I see. But the problem is I'm getting this error not when trying to implicitly cast result to vector, but when just calling these methods (createGraphicsPipelinesUnique & createComputePipelinesUnique): it still fails when I explicitly use .value, or even when I just call these methods without assigning result anywhere

**Comment by asuessenbach** [comment]
@YaaZ That sounds like a different problem.
Is it still a compile-time issue or a runtime issue?
Can you provide some code showcasing the problem?

**Comment by YaaZ** [comment]
@asuessenbach it is a compile-time issue, log is the same as in issue description and if I'm not mistaken, it appeared after MSVC update. I'll provide a code sample a bit later, but there's not going to be anything special with it

**Comment by asuessenbach** [comment]
@YaaZ Can you update your compiler to the latest version?

**Comment by YaaZ** [comment]
I checked it out and it turns out that indeed, this fix just didn't make it to 1.2.148.1. It fails even on simple calls like `device.createGraphicsPipelinesUnique({}, {});`, but I don't feel like building headers myself, so will just wait for the next release. Sorry for the confusion

Btw, updating MSVC brought even more issues 😭
